### ISSUE TITLE
Day-2 User Side & Admin Side

### ISSUE THREAD

**Issue by ShaswatSRaghuvansi** [ShaswatSRaghuvansi/squalid-direction-3013#2]
User Side -
- [x] Landing Page
- [x] Nav Bar
- [x] Content
- [x] Footer
- [x] Login & Register Page

Admin Side -
- [x] Admin Page Login
- [x] Admin Page dashboard

**Comment by Rohit1438** [comment]
Html Css Part done; tommorows work will be focused on JScript
